name: golang-build-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: windows-latest
    env:
      targetWin64Zip: ${{ github.event.repository.name }}-${{ github.ref_name }}-win64.zip
      targetWebAssemblyZip: ${{ github.event.repository.name }}-${{ github.ref_name }}-wasm.zip
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.0' # The Go version to download (if necessary) and use.
          
          
      - run: go get .
      
      - run: go build
        env:
          GOOS: windows
          GOARCH: amd64

      - run: go build -o build-webassembly\main.wasm  .\webassembly\main_js.go
        env:
          GOOS: js
          GOARCH: wasm
      
      - run: copy "%GOROOT%\misc\wasm\wasm_exec.js" build-webassembly\
        shell: cmd
    
      - name: Archive Release (win64)
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: ${{ github.event.repository.name }}.exe
          filename: "${{ env.targetWin64Zip }}"

      - name: Archive Release (webassembly)
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: build-webassembly
          filename: "${{ env.targetWebAssemblyZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.targetWin64Zip }},build-webassembly/${{ env.targetWebAssemblyZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
